"""video download markers

Revision ID: 8ed59e5b7392
Revises: d8a26c04c662
Create Date: 2025-12-23 02:10:13.895394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed59e5b7392'
down_revision: Union[str, Sequence[str], None] = 'd8a26c04c662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('download_jobs', 'progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('videos', sa.Column('last_download_job_id', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('downloaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'downloaded_at')
    op.drop_column('videos', 'last_download_job_id')
    op.alter_column('download_jobs', 'progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###
