"""download job timestamps progress

Revision ID: d8a26c04c662
Revises: 4973a6a31eea
Create Date: 2025-12-19 12:50:28.072524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a26c04c662'
down_revision: Union[str, Sequence[str], None] = '4973a6a31eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "download_jobs",
    sa.Column("progress", sa.Integer(), nullable=False, server_default=None),
)
    op.add_column('download_jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('download_jobs', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_jobs', 'finished_at')
    op.drop_column('download_jobs', 'started_at')
    op.drop_column('download_jobs', 'progress')
    # ### end Alembic commands ###
